### ISSUE TITLE
Error when creating UserList instance: UserList.__new__() got an unexpected keyword argument 'share_link'

### ISSUE THREAD

**Issue by bassettmason** [glensc/python-pytrakt#32]
Hello,

I've been using the PyTrakt library and ran into an issue while trying to create a new instance of the UserList class. Here is the relevant part of the code that causes the problem:

UserList.create(name="name", creator="name", description="description", privacy="public", display_numbers=True, allow_comments=True)

The share_link argument is not recognized, although it is a part of the UserListTuple NamedTuple.

ERROR:my_logger:Server error: UserList.__new__() got an unexpected keyword argument 'share_link'

user.get_list("playlist name") triggers the error

**Comment by glensc** [comment]
missing version information.

this has been fixed in https://github.com/glensc/python-pytrakt/pull/27

**Comment by bassettmason** [comment]
Thank you so much for your service sorry about the version, I must of been tired that day. I'm so happy you picked up pytrakt and kept things going thanks.
