### ISSUE TITLE
Take over the original PyPI project?

### ISSUE THREAD

**Issue by wfriesen** [glensc/python-pytrakt#40]
Now that trakt has removed the base url used in the source of this fork, the `trakt` package on PyPI is not usable. I've opened an issue there so that it's discoverable, not expecting a response: https://github.com/moogar0880/PyTrakt/issues/216

Maybe it would be possible to remove or take ownership of the `trakt` project now.

**Comment by glensc** [comment]
The owner of original repo is not responding:
- https://github.com/moogar0880/PyTrakt/issues/199
